#ifndef _UMAPDATA_H_
#define _UMAPDATA_H_

#include <string>
#include <vector>
#include <bitset>
#include "mtype.h"
#include "itype.h"
#include "output.h"
#include "mongroup.h"
#include "mapdata.h"
#include "omdata.h"
#include "mapdata.h"

const oter_t uoterlist[num_ter_types] = {
{"nothing",		'%',	c_white,	0, no_extras, false, false, 0, 0x0},
{"crater",		'O',	c_red,		2, field_extras, false, false, 0, 0x0},
{"field",		'.',	c_brown,	2, field_extras, false, false, 0, 0x0 /*0x2591*/},
{"forest",		'F',	c_green,	3, field_extras, false, false, 0, 0x234B},
{"forest",		'F',	c_green,	4, field_extras, false, false, 0, 0x1FA2},
{"swamp",		'F',	c_cyan,		4, field_extras, false, false, 0, 0x0},
{"highway",		'H',	c_dkgray,	2, road_extras, false, false, 0, 0x0},
{"highway",		'=',	c_dkgray,	2, road_extras, false, false, 0, 0x0},
{"BUG (omdata.h:oterlist)",			'%',	c_magenta,	0, no_extras, false, false, 0, 0x0},
{"road",          LINE_XOXO,	c_dkgray,	2, road_extras, false, false, 0, 0x0},
{"road",          LINE_OXOX,	c_dkgray,	2, road_extras, false, false, 0, 0x0},
{"road",          LINE_XXOO,	c_dkgray,	2, road_extras, false, false, 0, 0x0},
{"road",          LINE_OXXO,	c_dkgray,	2, road_extras, false, false, 0, 0x0},
{"road",          LINE_OOXX,	c_dkgray,	2, road_extras, false, false, 0, 0x0},
{"road",          LINE_XOOX,	c_dkgray,	2, road_extras, false, false, 0, 0x0},
{"road",          LINE_XXXO,	c_dkgray,	2, road_extras, false, false, 0, 0x0},
{"road",          LINE_XXOX,	c_dkgray,	2, road_extras, false, false, 0, 0x0},
{"road",          LINE_XOXX,	c_dkgray,	2, road_extras, false, false, 0, 0x0},
{"road",          LINE_OXXX,	c_dkgray,	2, road_extras, false, false, 0, 0x0},
{"road",          LINE_XXXX,	c_dkgray,	2, road_extras, false, false, 0, 0x0},
{"road, manhole", LINE_XXXX,	c_yellow,	2, road_extras, true, false, 0, 0x0},
{"bridge",		'|',	c_dkgray,	2, no_extras, false, false, 0, 0x0},
{"bridge",		'-',	c_dkgray,	2, no_extras, false, false, 0, 0x0},
{"river",		'R',	c_blue,		1, no_extras, false, false, 0, 0x0},
{"river bank",		'R',	c_ltblue,	1, no_extras, false, false, 0, 0x0},
{"river bank",		'R',	c_ltblue,	1, no_extras, false, false, 0, 0x0},
{"river bank",		'R',	c_ltblue,	1, no_extras, false, false, 0, 0x0},
{"river bank",		'R',	c_ltblue,	1, no_extras, false, false, 0, 0x0},
{"river bank",		'R',	c_ltblue,	1, no_extras, false, false, 0, 0x0},
{"river bank",		'R',	c_ltblue,	1, no_extras, false, false, 0, 0x0},
{"river bank",		'R',	c_ltblue,	1, no_extras, false, false, 0, 0x0},
{"river bank",		'R',	c_ltblue,	1, no_extras, false, false, 0, 0x0},
{"river bank",		'R',	c_ltblue,	1, no_extras, false, false, 0, 0x0},
{"river bank",		'R',	c_ltblue,	1, no_extras, false, false, 0, 0x0},
{"river bank",		'R',	c_ltblue,	1, no_extras, false, false, 0, 0x0},
{"river bank",		'R',	c_ltblue,	1, no_extras, false, false, 0, 0x0},
{"house",		'^',	c_ltgreen,	5, build_extras, false, false, 2, 0x2302},
{"house",		'>',	c_ltgreen,	5, build_extras, false, false, 2, 0x0},
{"house",		'v',	c_ltgreen,	5, build_extras, false, false, 2, 0x0},
{"house",		'<',	c_ltgreen,	5, build_extras, false, false, 2, 0x0},
{"house",		'^',	c_ltgreen,	5, build_extras, false, false, 2, 0x0},
{"house",		'>',	c_ltgreen,	5, build_extras, false, false, 2, 0x0},
{"house",		'v',	c_ltgreen,	5, build_extras, false, false, 2, 0x0},
{"house",		'<',	c_ltgreen,	5, build_extras, false, false, 2, 0x0},
{"parking lot",		'O',	c_dkgray,	1, build_extras, false, false, 2, 0x0},
{"park",		'O',	c_green,	2, build_extras, false, false, 2, 0x0},
{"gas station",		'^',	c_ltblue,	5, build_extras, false, false, 2, 0x0},
{"gas station",		'>',	c_ltblue,	5, build_extras, false, false, 2, 0x0},
{"gas station",		'v',	c_ltblue,	5, build_extras, false, false, 2, 0x0},
{"gas station",		'<',	c_ltblue,	5, build_extras, false, false, 2, 0x0},
{"pharmacy",		'^',	c_ltred,	5, build_extras, false, false, 2, 0x0},
{"pharmacy",		'>',	c_ltred,	5, build_extras, false, false, 2, 0x0},
{"pharmacy",		'v',	c_ltred,	5, build_extras, false, false, 2, 0x0},
{"pharmacy",		'<',	c_ltred,	5, build_extras, false, false, 2, 0x0},
{"doctor's office", 	'^',	   i_ltred,	5, build_extras, false, false, 2, 0x0},
{"doctor's office",  '>',    i_ltred, 5, build_extras, false, false, 2, 0x0},
{"doctor's office",  'v',    i_ltred,	5, build_extras, false, false, 2, 0x0},
{"doctor's office",  '<',    i_ltred,	5, build_extras, false, false, 2, 0x0},
{"office", 	'^',	c_ltgray,	5, build_extras, false, false, 2, 0x0},
{"office",		'>',	c_ltgray,	5, build_extras, false, false, 2, 0x0},
{"office",		'v',	c_ltgray,	5, build_extras, false, false, 2, 0x0},
{"office",		'<',	c_ltgray,	5, build_extras, false, false, 2, 0x0},
{"apartment tower", 'A', c_ltgreen,		5, no_extras, false, false, 2, 0x0},
{"apartment tower",	'A',	c_ltgreen,		5, no_extras, false, false, 2, 0x0},
{"apartment tower", 'A', c_ltgreen, 	5, no_extras, false, false, 2, 0x0},
{"apartment tower",	'A',	c_ltgreen,		5, no_extras, false, false, 2, 0x0},
{"office tower", 'T', i_ltgray,		5, no_extras, false, false, 2, 0x0},
{"office tower",	't',	i_ltgray,		5, no_extras, false, false, 2, 0x0},
{"tower parking", 'p',	i_ltgray,		5, no_extras, false, false, 2, 0x0},
{"tower parking",	'p',	i_ltgray,		5, no_extras, false, false, 2, 0x0},
{"church",		'C',	c_ltred,	5, build_extras, false, false, 2, 0x0},
{"church",		'C',	c_ltred,	5, build_extras, false, false, 2, 0x0},
{"church",		'C',	c_ltred,	5, build_extras, false, false, 2, 0x0},
{"church",		'C',	c_ltred,	5, build_extras, false, false, 2, 0x0},
{"cathedral", 'C', i_ltred, 	5, no_extras, false, false, 2, 0x0},
{"cathedral",	'C',	i_ltred,		5, no_extras, false, false, 2, 0x0},
{"cathedral basement", 'C',	i_ltred,		5, no_extras, false, false, 2, 0x0},
{"cathedral basement",	'C',	i_ltred,		5, no_extras, false, false, 2, 0x0},
{"grocery store",	'^',	c_green,	5, build_extras, false, false, 2, 0x0},
{"grocery store",	'>',	c_green,	5, build_extras, false, false, 2, 0x0},
{"grocery store",	'v',	c_green,	5, build_extras, false, false, 2, 0x0},
{"grocery store",	'<',	c_green,	5, build_extras, false, false, 2, 0x0},
{"hardware store",	'^',	c_cyan,		5, build_extras, false, false, 2, 0x0},
{"hardware store",	'>',	c_cyan,		5, build_extras, false, false, 2, 0x0},
{"hardware store",	'v',	c_cyan,		5, build_extras, false, false, 2, 0x0},
{"hardware store",	'<',	c_cyan,		5, build_extras, false, false, 2, 0x0},
{"electronics store",   '^',	c_yellow,	5, build_extras, false, false, 2, 0x0},
{"electronics store",   '>',	c_yellow,	5, build_extras, false, false, 2, 0x0},
{"electronics store",   'v',	c_yellow,	5, build_extras, false, false, 2, 0x0},
{"electronics store",   '<',	c_yellow,	5, build_extras, false, false, 2, 0x0},
{"sporting goods store",'^',	c_ltcyan,	5, build_extras, false, false, 2, 0x0},
{"sporting goods store",'>',	c_ltcyan,	5, build_extras, false, false, 2, 0x0},
{"sporting goods store",'v',	c_ltcyan,	5, build_extras, false, false, 2, 0x0},
{"sporting goods store",'<',	c_ltcyan,	5, build_extras, false, false, 2, 0x0},
{"liquor store",	'^',	c_magenta,	5, build_extras, false, false, 2, 0x0},
{"liquor store",	'>',	c_magenta,	5, build_extras, false, false, 2, 0x0},
{"liquor store",	'v',	c_magenta,	5, build_extras, false, false, 2, 0x0},
{"liquor store",	'<',	c_magenta,	5, build_extras, false, false, 2, 0x0},
{"gun store",		'^',	c_red,		5, build_extras, false, false, 2, 0x0},
{"gun store",		'>',	c_red,		5, build_extras, false, false, 2, 0x0},
{"gun store",		'v',	c_red,		5, build_extras, false, false, 2, 0x0},
{"gun store",		'<',	c_red,		5, build_extras, false, false, 2, 0x0},
{"clothing store",	'^',	c_blue,		5, build_extras, false, false, 2, 0x0},
{"clothing store",	'>',	c_blue,		5, build_extras, false, false, 2, 0x0},
{"clothing store",	'v',	c_blue,		5, build_extras, false, false, 2, 0x0},
{"clothing store",	'<',	c_blue,		5, build_extras, false, false, 2, 0x0},
{"library",		'^',	c_brown,	5, build_extras, false, false, 2, 0x0},
{"library",		'>',	c_brown,	5, build_extras, false, false, 2, 0x0},
{"library",		'v',	c_brown,	5, build_extras, false, false, 2, 0x0},
{"library",		'<',	c_brown,	5, build_extras, false, false, 2, 0x0},
{"restaurant",		'^',	c_pink,		5, build_extras, false, false, 2, 0x0},
{"restaurant",		'>',	c_pink,		5, build_extras, false, false, 2, 0x0},
{"restaurant",		'v',	c_pink,		5, build_extras, false, false, 2, 0x0},
{"restaurant",		'<',	c_pink,		5, build_extras, false, false, 2, 0x0},
{"fast food restaurant",    '^', c_pink,		5, build_extras, false, false, 2, 0x0},
{"fast food restaurant",    '>',	c_pink,		5, build_extras, false, false, 2, 0x0},
{"fast food restaurant",    'v',	c_pink,		5, build_extras, false, false, 2, 0x0},
{"fast food restaurant",    '<',	c_pink,		5, build_extras, false, false, 2, 0x0},
{"coffee shop",    '^',	c_pink,		5, build_extras, false, false, 2, 0x0},
{"coffee shop",    '>',	c_pink,		5, build_extras, false, false, 2, 0x0},
{"coffee shop",    'v',	c_pink,		5, build_extras, false, false, 2, 0x0},
{"coffee shop",    '<',	c_pink,		5, build_extras, false, false, 2, 0x0},
{"subway station",	'S',	c_yellow,	5, build_extras, true, false, 2, 0x0},
{"subway station",	'S',	c_yellow,	5, build_extras, true, false, 2, 0x0},
{"subway station",	'S',	c_yellow,	5, build_extras, true, false, 2, 0x0},
{"subway station",	'S',	c_yellow,	5, build_extras, true, false, 2, 0x0},
{"garage",              'O',    c_white,       5, build_extras, false, false, 2, 0x0},
{"garage",              'O',    c_white,       5, build_extras, false, false, 2, 0x0},
{"garage",              'O',    c_white,       5, build_extras, false, false, 2, 0x0},
{"garage",              'O',    c_white,       5, build_extras, false, false, 2, 0x0},
{"forest",              'F',	   c_green,	      5, field_extras, false, false, 0,0x0}, //lost cabin
{"cabin basement",      'C',    i_green,       5, build_extras, false, false, 0, 0x0},
{"cabin",              'C',    i_green,       5, build_extras, false, false, 2, 0x0},
{"dirt lot",		'O',	c_brown,	1, field_extras, false, false, 0, 0x0},
{"farm",              '^',    i_brown,       5, build_extras, false, false, 2, 0x0},
{"farm field",              '#',    i_brown,       5, field_extras, false, false, 2, 0x0},
{"police station",	'^',	h_yellow,	5, build_extras, false, false, 2, 0x0},
{"police station",	'>',	h_yellow,	5, build_extras, false, false, 2, 0x0},
{"police station",	'v',	h_yellow,	5, build_extras, false, false, 2, 0x0},
{"police station",	'<',	h_yellow,	5, build_extras, false, false, 2, 0x0},
{"bank",		'$',	c_ltgray,	5, no_extras, false, false, 2, 0x0},
{"bank",		'$',	c_ltgray,	5, no_extras, false, false, 2, 0x0},
{"bank",		'$',	c_ltgray,	5, no_extras, false, false, 2, 0x0},
{"bank",		'$',	c_ltgray,	5, no_extras, false, false, 2, 0x0},
{"bar",			'^',	i_magenta,		5, build_extras, false, false, 2, 0x0},
{"bar",			'>',	i_magenta,		5, build_extras, false, false, 2, 0x0},
{"bar",			'v',	i_magenta,		5, build_extras, false, false, 2, 0x0},
{"bar",			'<',	i_magenta,		5, build_extras, false, false, 2, 0x0},
{"pawn shop",		'^',	c_white,	5, build_extras, false, false, 2, 0x0},
{"pawn shop",		'>',	c_white,	5, build_extras, false, false, 2, 0x0},
{"pawn shop",		'v',	c_white,	5, build_extras, false, false, 2, 0x0},
{"pawn shop",		'<',	c_white,	5, build_extras, false, false, 2, 0x0},
{"mil. surplus",	'^',	i_ltgray,	5, build_extras, false, false, 2, 0x0},
{"mil. surplus",	'>',	i_ltgray,	5, build_extras, false, false, 2, 0x0},
{"mil. surplus",	'v',	i_ltgray,	5, build_extras, false, false, 2, 0x0},
{"mil. surplus",	'<',	i_ltgray,	5, build_extras, false, false, 2, 0x0},
{"furniture store",     '^',    i_brown,        5, build_extras, false, false, 2, 0x0},
{"furniture store",     '>',    i_brown,        5, build_extras, false, false, 2, 0x0},
{"furniture store",     'v',    i_brown,        5, build_extras, false, false, 2, 0x0},
{"furniture store",     '<',    i_brown,        5, build_extras, false, false, 2, 0x0},
{"abandoned storefront",        '^',    h_dkgray,       5, build_extras, false, false, 2, 0x0},
{"abandoned storefront",        '>',    h_dkgray,       5, build_extras, false, false, 2, 0x0},
{"abandoned storefront",        'v',    h_dkgray,       5, build_extras, false, false, 2, 0x0},
{"abandoned storefront",        '<',    h_dkgray,       5, build_extras, false, false, 2, 0x0},
{"megastore",		'+',	c_ltblue,	5, build_extras, false, false, 2, 0x0},
{"megastore",		'M',	c_blue,		5, build_extras, false, false, 2, 0x0},
{"hospital",		'H',	c_ltred,	5, build_extras, false, false, 2, 0x0},
{"hospital",		'H',	c_red,		5, build_extras, false, false, 2, 0x0},
{"public works", 'W',	c_ltgray,		5, no_extras, false, false, 2, 0x0},
{"public works",	'w',	c_ltgray,		5, no_extras, false, false, 2, 0x0},
{"regional school", 's', c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"regional school", 'S',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"regional school", 's',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"regional school", 's',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"regional school", 's',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"regional school", 's',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"regional school", 's',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"regional school", 's',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"regional school", 's',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"prison", 'p', i_ltblue, 	5, no_extras, false, false, 0, 0x0},
{"prison", 'P',	i_ltblue,		5, no_extras, false, false, 0, 0x0},
{"prison", 'p',	i_ltblue,		5, no_extras, false, false, 0, 0x0},
{"prison", 'p',	i_ltblue,		5, no_extras, false, false, 0, 0x0},
{"prison", 'p',	i_ltblue,		5, no_extras, false, false, 0, 0x0},
{"prison", 'p',	i_ltblue,		5, no_extras, false, false, 0, 0x0},
{"prison", 'p',	i_ltblue,		5, no_extras, false, false, 0, 0x0},
{"prison", 'p',	i_ltblue,		5, no_extras, false, false, 0, 0x0},
{"prison", 'p',	i_ltblue,		5, no_extras, false, false, 0, 0x0},
{"prison", 'p',	i_ltblue,		5, no_extras, false, false, 0, 0x0},
{"prison", 'p',	i_ltblue,		5, no_extras, false, false, 0, 0x0},
{"hotel parking", 'h', c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"hotel parking", 'h',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"hotel parking", 'h',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"hotel parking", 'h',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"hotel entrance", 'H',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"hotel parking", 'h',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"hotel tower", 'H',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"hotel tower", 'H',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"hotel tower", 'H',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"hotel basement", 'B',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"hotel basement", 'B',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"hotel basement", 'B',	c_ltblue,		5, no_extras, false, false, 2, 0x0},
{"mansion",		'M',	c_ltgreen,	5, build_extras, false, false, 2, 0x0},
{"mansion",		'M',	c_green,	5, build_extras, false, false, 2, 0x0},
{"fema camp",		'+',	c_blue,	5, build_extras, false, false, 0, 0x0},
{"fema camp",		'F',	i_blue,	5, build_extras, false, false, 0, 0x0},
{"radio station",  'X',    i_ltgray, 	5, build_extras, false, false, 0, 0x0},
{"radio station",  'X',    i_ltgray,		5, build_extras, false, false, 0, 0x0},
{"radio station",  'X',    i_ltgray,		5, build_extras, false, false, 0, 0x0},
{"radio station",  'X',    i_ltgray,		5, build_extras, false, false, 0, 0x0},
{"evac shelter",	'+',	c_white,	2, no_extras, true, false, 0, 0x0},
{"evac shelter",	'+',	c_white,	2, no_extras, false, true, 0, 0x0},
{"LMOE shelter",	'+',	c_red,	2, no_extras, true, false, 0, 0x0},
{"LMOE shelter",	'+',	c_red,	2, no_extras, false, true, 0, 0x0},
{"science lab",		'L',	c_ltblue,	5, no_extras, false, false, 0, 0x0},
{"science lab",		'L',	c_blue,		5, no_extras, true, false, 0, 0x0},
{"science lab",		'L',	c_ltblue,	5, no_extras, false, false, 0, 0x0},
{"science lab",		'L',	c_cyan,		5, no_extras, false, false, 0, 0x0},
{"nuclear plant",	'P',	c_ltgreen,	5, no_extras, false, false, 0, 0x0},
{"nuclear plant",	'P',	c_ltgreen,	5, no_extras, false, false, 0, 0x0},
{"military bunker",	'B',	c_dkgray,	2, no_extras, true, true, 0, 0x0},
{"military outpost",	'M',	c_dkgray,	2, build_extras, false, false, 0, 0x0},
{"missile silo",	'0',	c_ltgray,	2, no_extras, false, false, 0, 0x0},
{"missile silo",	'0',	c_ltgray,	2, no_extras, false, false, 0, 0x0},
{"strange temple",	'T',	c_magenta,	5, no_extras, true, false, 0, 0x0},
{"strange temple",	'T',	c_pink,		5, no_extras, true, false, 0, 0x0},
{"strange temple",	'T',	c_pink,		5, no_extras, false, false, 0, 0x0},
{"strange temple",	'T',	c_yellow,	5, no_extras, false, false, 0, 0x0},
{"sewage treatment",	'P',	c_red,		5, no_extras, true, false, 0, 0x0},
{"sewage treatment",	'P',	c_green,	5, no_extras, false, true, 0, 0x0},
{"sewage treatment",	'P',	c_green,	5, no_extras, false, false, 0, 0x0},
{"mine entrance",	'M',	c_ltgray,	5, no_extras, true, false, 0, 0x0},
{"mine shaft",		'O',	c_dkgray,	5, no_extras, true, true, 0, 0x0},
{"mine",		'M',	c_brown,	2, no_extras, false, false, 0, 0x0},
{"mine",		'M',	c_brown,	2, no_extras, false, false, 0, 0x0},
{"mine",		'M',	c_brown,	2, no_extras, false, false, 0, 0x0},
{"spiral cavern",	'@',	c_pink,		2, no_extras, false, false, 0, 0x0},
{"spiral cavern",	'@',	c_pink,		2, no_extras, false, false, 0, 0x0},
{"radio tower",         'X',    c_ltgray,       2, no_extras, false, false, 0, 0x0},
{"toxic waste dump",	'D',	c_pink,		2, no_extras, false, false, 0, 0x0},
{"hazardous waste sarcophagus", 'X', c_ltred,		5, no_extras, false, false, 0, 0x0},
{"hazardous waste sarcophagus",	'X',	c_pink,		5, no_extras, false, false, 0, 0x0},
{"hazardous waste sarcophagus", 'X',	c_pink,		5, no_extras, false, false, 0, 0x0},
{"hazardous waste sarcophagus",	'X',	c_pink,		5, no_extras, false, false, 0, 0x0},
{"cave",		'C',	c_brown,	2, field_extras, false, false, 0, 0x0},
{"rat cave",		'C',	c_dkgray,	2, no_extras, true, false, 0, 0x0},
{"bee hive",		'8',	c_yellow,	3, field_extras, false, false, 0, 0x0},
{"fungal bloom",	'T',	c_ltgray,	2, field_extras, false, false, 0, 0x0},
{"forest",		'F',	c_green,	3, field_extras, false, false, 0,0x0}, // Spider pit
{"cavern",		'0',	c_ltgray,	5, no_extras, false, false, 0,0x0}, // Spider pit
{"anthill",		'%',	c_brown,	2, no_extras, true, false, 0, 0x0},
{"slime pit",		'~',	c_ltgreen,	2, no_extras, false, false, 0, 0x0},
{"slime pit",		'~',	c_ltgreen,	2, no_extras, true, false, 0, 0x0},
{"triffid grove",	'T',	c_ltred,	5, no_extras, true, false, 0, 0x0},
{"triffid roots",	'T',	c_ltred,	5, no_extras, true, true, 0, 0x0},
{"triffid heart",	'T',	c_red,		5, no_extras, false, true, 0, 0x0},
{"basement",		'O',	c_dkgray,	5, no_extras, false, true, 0, 0x0},
{"cavern",		'0',	c_ltgray,	5, no_extras, false, false, 0, 0x0},
{"solid rock",		'%',	c_dkgray,	5, no_extras, false, false, 0, 0x0},
{"rift",		'^',	c_red,		2, no_extras, false, false, 0, 0x0},
{"hellmouth",		'^',	c_ltred,	2, no_extras, true, false, 0, 0x0},
{"subway station",	'S',	c_yellow,	5, subway_extras, false, true, 0, 0x0},
{"subway",        LINE_XOXO,	c_dkgray,	5, subway_extras, false, false, 0, 0x0},
{"subway",        LINE_OXOX,	c_dkgray,	5, subway_extras, false, false, 0, 0x0},
{"subway",        LINE_XXOO,	c_dkgray,	5, subway_extras, false, false, 0, 0x0},
{"subway",        LINE_OXXO,	c_dkgray,	5, subway_extras, false, false, 0, 0x0},
{"subway",        LINE_OOXX,	c_dkgray,	5, subway_extras, false, false, 0, 0x0},
{"subway",        LINE_XOOX,	c_dkgray,	5, subway_extras, false, false, 0, 0x0},
{"subway",        LINE_XXXO,	c_dkgray,	5, subway_extras, false, false, 0, 0x0},
{"subway",        LINE_XXOX,	c_dkgray,	5, subway_extras, false, false, 0, 0x0},
{"subway",        LINE_XOXX,	c_dkgray,	5, subway_extras, false, false, 0, 0x0},
{"subway",        LINE_OXXX,	c_dkgray,	5, subway_extras, false, false, 0, 0x0},
{"subway",        LINE_XXXX,	c_dkgray,	5, subway_extras, false, false, 0, 0x0},
{"sewer",         LINE_XOXO,	c_green,	5, no_extras, false, false, 0, 0x0},
{"sewer",         LINE_OXOX,	c_green,	5, no_extras, false, false, 0, 0x0},
{"sewer",         LINE_XXOO,	c_green,	5, no_extras, false, false, 0, 0x0},
{"sewer",         LINE_OXXO,	c_green,	5, no_extras, false, false, 0, 0x0},
{"sewer",         LINE_OOXX,	c_green,	5, no_extras, false, false, 0, 0x0},
{"sewer",         LINE_XOOX,	c_green,	5, no_extras, false, false, 0, 0x0},
{"sewer",         LINE_XXXO,	c_green,	5, no_extras, false, false, 0, 0x0},
{"sewer",         LINE_XXOX,	c_green,	5, no_extras, false, false, 0, 0x0},
{"sewer",         LINE_XOXX,	c_green,	5, no_extras, false, false, 0, 0x0},
{"sewer",         LINE_OXXX,	c_green,	5, no_extras, false, false, 0, 0x0},
{"sewer",         LINE_XXXX,	c_green,	5, no_extras, false, false, 0, 0x0},
{"ant tunnel",    LINE_XOXO,	c_brown,	5, no_extras, false, false, 0, 0x0},
{"ant tunnel",    LINE_OXOX,	c_brown,	5, no_extras, false, false, 0, 0x0},
{"ant tunnel",    LINE_XXOO,	c_brown,	5, no_extras, false, false, 0, 0x0},
{"ant tunnel",    LINE_OXXO,	c_brown,	5, no_extras, false, false, 0, 0x0},
{"ant tunnel",    LINE_OOXX,	c_brown,	5, no_extras, false, false, 0, 0x0},
{"ant tunnel",    LINE_XOOX,	c_brown,	5, no_extras, false, false, 0, 0x0},
{"ant tunnel",    LINE_XXXO,	c_brown,	5, no_extras, false, false, 0, 0x0},
{"ant tunnel",    LINE_XXOX,	c_brown,	5, no_extras, false, false, 0, 0x0},
{"ant tunnel",    LINE_XOXX,	c_brown,	5, no_extras, false, false, 0, 0x0},
{"ant tunnel",    LINE_OXXX,	c_brown,	5, no_extras, false, false, 0, 0x0},
{"ant tunnel",    LINE_XXXX,	c_brown,	5, no_extras, false, false, 0, 0x0},
{"ant food storage",	'O',	c_green,	5, no_extras, false, false, 0, 0x0},
{"ant larva chamber",	'O',	c_white,	5, no_extras, false, false, 0, 0x0},
{"ant queen chamber",	'O',	c_red,		5, no_extras, false, false, 0, 0x0},
{"tutorial room",	'O',	c_cyan,		5, no_extras, false, false, 0,0x0}
};

const ter_t uterlist[num_terrain_types] = {  // MUST match enum ter_id above!
{"nothing",             ' ', c_white,   2, tr_null,
    mfb(transparent)|mfb(diggable), &iexamine::none, 0x0},
{"empty space",         ' ', c_black,   2, tr_ledge,
    mfb(transparent), &iexamine::none, 0x0},
{"dirt",	            '.', c_brown,   2, tr_null,
    mfb(transparent)|mfb(diggable)|mfb(flat), &iexamine::none, 0x0},
{"sand",	            '.', c_yellow,  2, tr_null,
    mfb(transparent)|mfb(diggable)|mfb(flat), &iexamine::none, 0x0},
{"mound of dirt",       '#', c_brown,   3, tr_null,
    mfb(transparent)|mfb(diggable), &iexamine::none, 0x0},
{"shallow pit",	        '0', c_yellow,  8, tr_null,
    mfb(transparent)|mfb(diggable), &iexamine::none, 0x0},
{"pit",                 '0', c_brown,   10, tr_pit,
    mfb(transparent)|mfb(diggable), &iexamine::pit, 0x0},
{"corpse filled pit",   '#', c_green,   5, tr_null,
    mfb(transparent)|mfb(diggable), &iexamine::none, 0x0},
{"covered pit",         '#', c_ltred,   2, tr_null,
    mfb(transparent), &iexamine::pit_covered, 0x0},
{"spiked pit",          '0', c_ltred,  10, tr_spike_pit,
    mfb(transparent)|mfb(diggable), &iexamine::pit, 0x0},
{"covered spiked pit",  '#', c_ltred,   2, tr_null,
    mfb(transparent), &iexamine::pit_covered, 0x0},
{"rock floor",          '.', c_ltgray,  2, tr_null,
    mfb(transparent)|mfb(indoors)|mfb(flat), &iexamine::none, 0x0},
{"pile of rubble",      '^', c_ltgray,  4, tr_null,
    mfb(transparent)|mfb(rough)|mfb(diggable), &iexamine::rubble, 0x0},
{"pile of ash",         '#', c_ltgray,  2, tr_null,
    mfb(transparent)|mfb(diggable), &iexamine::rubble, 0x0},
{"twisted metal",       '#', c_cyan,    5, tr_null,
    mfb(transparent)|mfb(rough)|mfb(sharp)|mfb(place_item), &iexamine::wreckage, 0x0},
{"metal wreckage",      '#', c_cyan,    5, tr_null,
    mfb(transparent)|mfb(rough)|mfb(sharp)|mfb(place_item), &iexamine::wreckage, 0x0},
{"grass",	            '.', c_green,   2, tr_null,
    mfb(transparent)|mfb(diggable)|mfb(flat), &iexamine::none, 0x0},
{"metal floor",         '.', c_ltcyan,  2, tr_null,
    mfb(transparent)|mfb(indoors)|mfb(flat), &iexamine::none, 0x0},
{"pavement",	        '.', c_dkgray,  2, tr_null,
    mfb(transparent)|mfb(flat), &iexamine::none, 0x0},
{"yellow pavement",     '.', c_yellow,  2, tr_null,
    mfb(transparent)|mfb(flat), &iexamine::none, 0x0},
{"sidewalk",            '.', c_ltgray,  2, tr_null,
    mfb(transparent)|mfb(flat), &iexamine::none, 0x0},
{"floor",	            '.', c_cyan,    2, tr_null,
    mfb(transparent)|mfb(l_flammable)|mfb(supports_roof)|mfb(collapses)|mfb(indoors)|mfb(flat),
    &iexamine::none, 0x0},
{"dirt floor",	        '.', c_brown,   2, tr_null,  //Dirt Floor, must have roofs!
    mfb(transparent)|mfb(diggable)|mfb(supports_roof)|mfb(collapses)|mfb(indoors)|mfb(flat),
    &iexamine::none, 0x0},
{"metal grate",         '#', c_dkgray,  2, tr_null,
    mfb(transparent), &iexamine::none, 0x0},
{"slime",               '~', c_green,   6, tr_null,
    mfb(transparent)|mfb(container)|mfb(flammable2)|mfb(place_item), &iexamine::none, 0x0},
{"walkway",             '#', c_yellow,  2, tr_null,
    mfb(transparent), &iexamine::none, 0x0},
{"floor",	            '.', c_white,   2, tr_null, // Skylight
    mfb(transparent)|mfb(l_flammable)|mfb(supports_roof)|mfb(collapses)|mfb(flat), &iexamine::none, 0x0},
{"floor",	            '.', c_white,   2, tr_null,
    mfb(transparent)|mfb(l_flammable)|mfb(supports_roof)|mfb(collapses)|mfb(indoors)|mfb(flat),
    &iexamine::none, 0x0}, // Emergency Light
{"floor",	            '.', c_white,   2, tr_null,
    mfb(transparent)|mfb(l_flammable)|mfb(supports_roof)|mfb(collapses)|mfb(indoors)|mfb(flat),
    &iexamine::none, 0x0}, // Regular Light
{"half-built wall",     '#', c_brown,   4, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(flammable2)|mfb(noitem), &iexamine::none, 0x0},
{"log wall",            '#', c_brown,   0, tr_null,
    mfb(bashable)|mfb(flammable)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"chipped log wall",    '#', c_brown,   0, tr_null,
    mfb(bashable)|mfb(flammable)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"broken log wall",     '&', c_brown,   0, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(flammable2)|mfb(noitem)|
    mfb(supports_roof), &iexamine::none, 0x0},
{"palisade wall",       '#', c_brown,   0, tr_null,
    mfb(bashable)|mfb(flammable)|mfb(noitem)|mfb(supports_roof)|mfb(transparent),
    &iexamine::none, 0x0},
{"palisade gate",       '+', c_ltred,   0, tr_null,
    mfb(bashable)|mfb(flammable)|mfb(noitem)|mfb(supports_roof)|mfb(door)|mfb(transparent),
    &iexamine::none, 0x0},
{"dirt",                '.', c_brown,   2, tr_null,
    mfb(transparent)|mfb(flammable)|mfb(supports_roof)|mfb(flat), &iexamine::none, 0x0}, // Open palisade gate
{"half-built wall",     '#', c_ltred,   4, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(flammable2)|mfb(noitem), &iexamine::none, 0x0},
{"wooden wall",         '#', c_ltred,   0, tr_null,
    mfb(bashable)|mfb(flammable)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"chipped wood wall",   '#', c_ltred,   0, tr_null,
    mfb(bashable)|mfb(flammable)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"broken wood wall",    '&', c_ltred,   0, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(flammable2)|mfb(noitem)|
    mfb(supports_roof), &iexamine::none, 0x0},
{"wall",          LINE_XOXO, c_ltgray,  0, tr_null,
    mfb(flammable)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"wall",          LINE_OXOX, c_ltgray,  0, tr_null,
    mfb(flammable)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"concrete wall", LINE_XOXO, c_dkgray,  0, tr_null,
    mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"concrete wall", LINE_OXOX, c_dkgray,  0, tr_null,
    mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"metal wall",    LINE_XOXO, c_cyan,    0, tr_null,
    mfb(noitem)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"metal wall",    LINE_OXOX, c_cyan,    0, tr_null,
    mfb(noitem)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"glass wall",    LINE_XOXO, c_ltcyan,  0, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"glass wall",    LINE_OXOX, c_ltcyan,  0, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"glass wall",    LINE_XOXO, c_ltcyan,  0, tr_null, // Alarmed
    mfb(transparent)|mfb(bashable)|mfb(alarmed)|mfb(noitem)|
    mfb(supports_roof), &iexamine::none, 0x0},
{"glass wall",    LINE_OXOX, c_ltcyan,  0, tr_null, // Alarmed
    mfb(transparent)|mfb(bashable)|mfb(alarmed)|mfb(noitem)|
    mfb(supports_roof), &iexamine::none, 0x0},
{"reinforced glass", LINE_XOXO, c_ltcyan,  0, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"reinforced glass", LINE_OXOX, c_ltcyan,  0, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"metal bars",          '"', c_ltgray,  0, tr_null,
    mfb(transparent)|mfb(noitem), &iexamine::none, 0x0},
{"closed wood door",    '+', c_brown,   0, tr_null,
    mfb(bashable)|mfb(flammable2)|mfb(door)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"damaged wood door",   '&', c_brown,   0, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(flammable2)|mfb(noitem)|
    mfb(supports_roof), &iexamine::none, 0x0},
{"open wood door",      '\'', c_brown,  2, tr_null,
    mfb(flammable2)|mfb(transparent)|mfb(supports_roof)|mfb(flat), &iexamine::none, 0x0},
{"closed wood door",    '+', c_brown,   0, tr_null,	// Locked from all directions
    mfb(bashable)|mfb(flammable2)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"closed wood door",    '+', c_brown,   0, tr_null,	// Actually locked
    mfb(bashable)|mfb(flammable2)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"closed wood door",    '+', c_brown,   0, tr_null, // Locked and alarmed
    mfb(bashable)|mfb(flammable2)|mfb(alarmed)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"empty door frame",    '.', c_brown,   2, tr_null,
    mfb(transparent)|mfb(supports_roof)|mfb(flat), &iexamine::none, 0x0},
{"locked wire gate",    '+', c_cyan,    0, tr_null,
    mfb(transparent)|mfb(supports_roof), &iexamine::none, 0x0},
{"closed wooden gate",  '+', c_brown,   3, tr_null,
    mfb(transparent)|mfb(supports_roof) |mfb(bashable)|mfb(flammable2), &iexamine::none, 0x0},
{"open wooden gate",    '.', c_brown,   2, tr_null,
    mfb(transparent)|mfb(supports_roof) |mfb(bashable)|mfb(flammable2)|mfb(flat), &iexamine::none, 0x0},
{"closed wire gate",    '+', c_cyan,    0, tr_null,
    mfb(transparent)|mfb(supports_roof), &iexamine::none, 0x0},
{"open wire gate",      '.', c_cyan,    2, tr_null,
    mfb(transparent)|mfb(supports_roof)|mfb(flat), &iexamine::none, 0x0},
{"boarded up door",     '#', c_brown,   0, tr_null,
    mfb(bashable)|mfb(flammable2)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"closed metal door",   '+', c_cyan,    0, tr_null,
    mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"open metal door",     '\'', c_cyan,   2, tr_null,
    mfb(transparent)|mfb(supports_roof)|mfb(flat), &iexamine::none, 0x0},
{"closed metal door",   '+', c_cyan,    0, tr_null, // Actually locked
    mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"closed bar door",     '+', c_cyan,    0, tr_null,// unlocked, only created at map gen
    mfb(transparent)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"open bar door",       '\'', c_cyan,   2, tr_null,
    mfb(transparent)|mfb(supports_roof)|mfb(flat), &iexamine::none, 0x0},
{"closed bar door",     '+', c_cyan,    0, tr_null, // locked
    mfb(transparent)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"closed glass door",   '+', c_ltcyan,  0, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(door)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"open glass door",     '\'', c_ltcyan, 2, tr_null,
    mfb(transparent)|mfb(supports_roof)|mfb(flat), &iexamine::none, 0x0},
{"makeshift portcullis", '&', c_cyan,   0, tr_null,
    mfb(noitem), &iexamine::none, 0x0},
{"steel compactor",     '&', c_green,   0, tr_null,
    mfb(transparent), &iexamine::recycler, 0x0},
{"window",	            '"', c_ltcyan,  0, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(flammable)|mfb(noitem)|
    mfb(supports_roof)|mfb(deconstruct), &iexamine::none, 0x0}, // Plain Ol' window
{"taped window",        '"', c_dkgray,  0, tr_null,
    mfb(bashable)|mfb(flammable)|mfb(noitem)| mfb(supports_roof)| mfb(reduce_scent),
    &iexamine::none, 0x0}, // Regular window
{"window",	            '"', c_ltcyan,  0, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(flammable)|mfb(noitem)|
    mfb(supports_roof)|mfb(deconstruct), &iexamine::none, 0x0}, //has curtains
{"taped window",        '"', c_dkgray,  0, tr_null,
    mfb(bashable)|mfb(flammable)|mfb(noitem)| mfb(supports_roof)| mfb(reduce_scent),
    &iexamine::none, 0x0}, // Curtain window
{"open window",         '\'', c_ltcyan, 4, tr_null,
    mfb(transparent)|mfb(flammable)|mfb(noitem)| mfb(supports_roof), &iexamine::none, 0x0},
{"closed curtains",     '"', c_dkgray,  0, tr_null,
    mfb(bashable)|mfb(flammable)|mfb(noitem)| mfb(supports_roof), &iexamine::none, 0x0},
{"window",	            '"', c_ltcyan,  0, tr_null, // Actually alarmed
    mfb(transparent)|mfb(bashable)|mfb(flammable)|mfb(alarmed)|mfb(noitem)|
    mfb(supports_roof), &iexamine::none, 0x0},
{"taped window",        '"', c_dkgray,  0, tr_null,
    mfb(bashable)|mfb(flammable)|mfb(noitem)| mfb(supports_roof)|mfb(alarmed)|
    mfb(reduce_scent), &iexamine::none, 0x0}, //Alarmed, duh.
{"empty window",        '0', c_yellow,  8, tr_null,
    mfb(transparent)|mfb(flammable)|mfb(supports_roof), &iexamine::none, 0x0},
{"window frame",        '0', c_ltcyan,  8, tr_null,
    mfb(transparent)|mfb(sharp)|mfb(flammable)|mfb(noitem)|
    mfb(supports_roof), &iexamine::none, 0x0},
{"boarded up window",   '#', c_brown,   0, tr_null,
    mfb(bashable)|mfb(flammable)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"high stained glass window", '"', c_ltgreen,  0, tr_null,
    mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"high stained glass window", '"', c_ltred,  0, tr_null,
    mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"high stained glass window", '"', c_ltblue,  0, tr_null,
    mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"solid rock",          '#', c_white,   0, tr_null,
    mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"odd fault",           '#', c_magenta, 0, tr_null,
    mfb(noitem)|mfb(supports_roof), &iexamine::fault, 0x0},
{"paper wall",          '#', c_white,   0, tr_null,
    mfb(bashable)|mfb(flammable2)|mfb(noitem), &iexamine::none, 0x0},
{"tree",	            '7', c_green,   0, tr_null,
    mfb(flammable2)|mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"young tree",          '1', c_green,   4, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(flammable2)|mfb(noitem), &iexamine::none, 0x0},
{"apple tree",          '7', c_ltgreen, 0, tr_null,
    mfb(flammable2)|mfb(noitem)|mfb(supports_roof), &iexamine::tree_apple, 0x0},
{"underbrush",          '#', c_ltgreen, 6, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(diggable)|mfb(container)|
    mfb(flammable2)|mfb(thin_obstacle)|mfb(place_item), &iexamine::shrub_wildveggies, 0x0},
{"shrub",               '#', c_green,   8, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(container)|mfb(flammable2)|
    mfb(thin_obstacle)|mfb(place_item), &iexamine::none, 0x0},
{"blueberry bush",      '#', c_ltgreen, 8, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(container)|mfb(flammable2)|mfb(thin_obstacle),
    &iexamine::shrub_blueberry, 0x0},
{"strawberry bush",     '#', c_ltgreen, 8, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(container)|mfb(flammable2)|mfb(thin_obstacle),
    &iexamine::shrub_strawberry, 0x0},
{"tree trunk",          '1', c_brown,   4, tr_null,
	   mfb(transparent)|mfb(flammable2)|mfb(diggable), &iexamine::none, 0x0},
{"root wall",           '#', c_brown,   0, tr_null,
    mfb(noitem)|mfb(supports_roof), &iexamine::none, 0x0},
{"wax wall",            '#', c_yellow,  0, tr_null,
    mfb(flammable2)|mfb(noitem)|mfb(supports_roof)|mfb(place_item), &iexamine::none, 0x0},
{"wax floor",           '.', c_yellow,  2, tr_null,
    mfb(transparent)|mfb(l_flammable)|mfb(indoors)|mfb(flat), &iexamine::none, 0x0},
{"picket fence",        '|', c_brown,   3, tr_null,
    mfb(bashable)|mfb(transparent)|mfb(diggable)|mfb(flammable2)|mfb(noitem)|mfb(thin_obstacle),
    &iexamine::none, 0x0},
{"picket fence",        '-', c_brown,   3, tr_null,
    mfb(bashable)|mfb(transparent)|mfb(diggable)|mfb(flammable2)|mfb(noitem)|mfb(thin_obstacle),
    &iexamine::none, 0x0},
{"chain link fence",    '|', c_cyan,    0, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(noitem)|mfb(thin_obstacle)|mfb(supports_roof), &iexamine::chainfence, 0x0},
{"chain link fence",    '-', c_cyan,    0, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(noitem)|mfb(thin_obstacle)|mfb(supports_roof), &iexamine::chainfence, 0x0},
{"metal post",          '#', c_cyan,    2, tr_null,
    mfb(transparent)|mfb(thin_obstacle), &iexamine::none, 0x0},
{"fence post",          '#', c_brown,   2, tr_null,
    mfb(transparent)|mfb(thin_obstacle), &iexamine::fence_post, 0x0},
{"wire fence",          '$', c_blue,    4, tr_null,
    mfb(transparent)|mfb(thin_obstacle), &iexamine::remove_fence_wire, 0x0},
{"barbed wire fence",   '$', c_blue,    4, tr_null,
    mfb(transparent)|mfb(sharp)|mfb(thin_obstacle), &iexamine::remove_fence_barbed, 0x0},
{"rope fence",          '$', c_brown,   3, tr_null,
    mfb(transparent)|mfb(thin_obstacle), &iexamine::remove_fence_rope, 0x0},
{"railing",             '|', c_yellow,  3, tr_null,
   	mfb(transparent)|mfb(noitem)|mfb(thin_obstacle), &iexamine::none, 0x0},
{"railing",             '-', c_yellow,  3, tr_null,
   	mfb(transparent)|mfb(noitem)|mfb(thin_obstacle), &iexamine::none, 0x0},
{"marloss bush",        '1', c_dkgray,  0, tr_null,
	   mfb(transparent)|mfb(bashable)|mfb(flammable2), &iexamine::none, 0x0},
{"fungal bed",          '#', c_dkgray,  3, tr_null,
	   mfb(transparent)|mfb(flammable2)|mfb(diggable), &iexamine::none, 0x0},
{"fungal tree",         '7', c_dkgray,  0, tr_null,
	   mfb(flammable2)|mfb(noitem), &iexamine::none, 0x0},
{"shallow water",       '~', c_ltblue,  5, tr_null,
	   mfb(transparent)|mfb(liquid)|mfb(swimmable), &iexamine::water_source, 0x0},
{"deep water",          '~', c_blue,    0, tr_null,
	   mfb(transparent)|mfb(liquid)|mfb(swimmable), &iexamine::water_source, 0x0},
{"pool water",          '~', c_ltblue,  5, tr_null,
    mfb(transparent)|mfb(liquid)|mfb(swimmable)|mfb(indoors),
    &iexamine::water_source, 0x0},
{"sewage",              '~', c_ltgreen, 6, tr_null,
	   mfb(transparent)|mfb(swimmable), &iexamine::water_source, 0x0},
{"lava",                '~', c_red,     4, tr_lava,
        mfb(transparent)|mfb(liquid)|mfb(destroy_item), &iexamine::none, 0x0},
{"sandbox",             '#', c_yellow,  3, tr_null,
   	mfb(transparent)|mfb(deconstruct), &iexamine::none, 0x0},
{"slide",               '#', c_ltcyan,  4, tr_null,
   	mfb(transparent)|mfb(deconstruct), &iexamine::none, 0x0},
{"monkey bars",         '#', c_cyan,    4, tr_null,
   	mfb(transparent)|mfb(deconstruct), &iexamine::none, 0x0},
{"backboard",           '7', c_red,     0, tr_null,
	   mfb(transparent)|mfb(deconstruct), &iexamine::none, 0x0},
{"gasoline pump",       '&', c_red,     0, tr_null,
	   mfb(transparent)|mfb(explodes)|mfb(noitem)|mfb(sealed)|mfb(container), &iexamine::gaspump, 0x0},
{"smashed gas pump",    '&', c_ltred,   0, tr_null,
	   mfb(transparent)|mfb(noitem), &iexamine::none, 0x0},
{"broken generator",    '&', c_ltgray,  0, tr_null,
	   mfb(transparent)|mfb(noitem), &iexamine::none, 0x0},
{"missile",             '#', c_ltblue,  0, tr_null,
	   mfb(explodes)|mfb(noitem), &iexamine::none, 0x0},
{"blown-out missile",   '#', c_ltgray,  0, tr_null,
	   mfb(noitem), &iexamine::none, 0x0},
{"radio tower",         '&', c_ltgray,  0, tr_null,
	   mfb(noitem), &iexamine::none, 0x0},
{"radio controls",      '6', c_green,   0, tr_null,
	   mfb(transparent)|mfb(bashable)|mfb(noitem), &iexamine::none, 0x0},
{"broken console",      '6', c_ltgray,  0, tr_null,
	   mfb(transparent)|mfb(noitem)|mfb(collapses)|mfb(indoors), &iexamine::none, 0x0},
{"computer console",    '6', c_blue,    0, tr_null,
	   mfb(transparent)|mfb(console)|mfb(noitem)|mfb(collapses)|mfb(indoors), &iexamine::none, 0x0},
{"mechanical winch",    '6', c_cyan_red, 0, tr_null,
    mfb(transparent)|mfb(noitem)|mfb(collapses), &iexamine::controls_gate, 0x0},
{"mechanical winch",    '6', c_cyan_red, 0, tr_null,
    mfb(transparent)|mfb(noitem)|mfb(collapses), &iexamine::controls_gate, 0x0},
{"rope and pulley",     '|', c_brown,   0, tr_null,
    mfb(transparent)|mfb(noitem)|mfb(collapses), &iexamine::controls_gate, 0x0},
{"rope and pulley",     '|', c_brown,   0, tr_null,
    mfb(transparent)|mfb(noitem)|mfb(collapses), &iexamine::controls_gate, 0x0},
{"sewage pipe",         '1', c_ltgray,  0, tr_null,
   	mfb(transparent), &iexamine::none, 0x0},
{"sewage pump",         '&', c_ltgray,  0, tr_null,
   	mfb(noitem), &iexamine::none, 0x0},
{"centrifuge",          '{', c_magenta, 0, tr_null,
   	mfb(transparent), &iexamine::none, 0x0},
{"column",              '1', c_ltgray,  0, tr_null,
	   mfb(flammable), &iexamine::none, 0x0},
{"cloning vat",         '0', c_ltcyan,  0, tr_null,
    mfb(transparent)|mfb(bashable)|mfb(sealed)|mfb(place_item), &iexamine::none, 0x0},
{"stairs down",         '>', c_yellow,  2, tr_null,
    mfb(transparent)|mfb(goes_down)|mfb(place_item), &iexamine::none, 0x0},
{"stairs up",           '<', c_yellow,  2, tr_null,
    mfb(transparent)|mfb(goes_up)|mfb(place_item), &iexamine::none, 0x0},
{"manhole",             '>', c_dkgray,  2, tr_null,
    mfb(transparent)|mfb(goes_down)|mfb(place_item), &iexamine::none, 0x0},
{"ladder",              '<', c_dkgray,  2, tr_null,
    mfb(transparent)|mfb(goes_up)|mfb(place_item), &iexamine::none, 0x0},
{"ladder",              '>', c_dkgray,  2, tr_null,
    mfb(transparent)|mfb(goes_down)|mfb(place_item), &iexamine::none, 0x0},
{"downward slope",      '>', c_brown,   2, tr_null,
    mfb(transparent)|mfb(goes_down)|mfb(place_item), &iexamine::none, 0x0},
{"upward slope",        '<', c_brown,   2, tr_null,
    mfb(transparent)|mfb(goes_up)|mfb(place_item), &iexamine::none, 0x0},
{"rope leading up",     '<', c_white,   2, tr_null,
   	mfb(transparent)|mfb(goes_up), &iexamine::none, 0x0},
{"manhole cover",       '0', c_dkgray,  2, tr_null,
	   mfb(transparent), &iexamine::none, 0x0},
{"card reader",	        '6', c_pink,    0, tr_null,	// Science
	   mfb(noitem), &iexamine::cardreader, 0x0},
{"card reader",	        '6', c_pink,    0, tr_null,	// Military
	   mfb(noitem), &iexamine::cardreader, 0x0},
{"broken card reader",  '6',c_ltgray,   0, tr_null,
	   mfb(noitem), &iexamine::none, 0x0},
{"slot machine",        '6', c_green,   0, tr_null,
	   mfb(bashable)|mfb(noitem)|mfb(indoors), &iexamine::slot_machine, 0x0},
{"elevator controls",   '6', c_ltblue,  0, tr_null,
    mfb(noitem)|mfb(indoors), &iexamine::elevator, 0x0},
{"powerless controls",  '6',c_ltgray,   0, tr_null,
    mfb(noitem)|mfb(indoors), &iexamine::none, 0x0},
{"elevator",            '.', c_magenta, 2, tr_null,
    mfb(indoors)|mfb(transparent), &iexamine::none, 0x0},
{"dark pedestal",       '&', c_dkgray,  0, tr_null,
	   mfb(transparent), &iexamine::pedestal_wyrm, 0x0},
{"light pedestal",      '&', c_white,   0, tr_null,
	   mfb(transparent), &iexamine::pedestal_temple, 0x0},
{"red stone",           '#', c_red,     0, tr_null,
	   0, &iexamine::none, 0x0},
{"green stone",         '#', c_green,   0, tr_null,
	   0, &iexamine::none, 0x0},
{"blue stone",          '#', c_blue,    0, tr_null,
	   0, &iexamine::none, 0x0},
{"red floor",           '.', c_red,     2, tr_null,
	   mfb(transparent)|mfb(flat), &iexamine::none, 0x0},
{"green floor",         '.', c_green,   2, tr_null,
	   mfb(transparent)|mfb(flat), &iexamine::none, 0x0},
{"blue floor",          '.', c_blue,    2, tr_null,
	   mfb(transparent)|mfb(flat), &iexamine::none, 0x0},
{"yellow switch",       '6', c_yellow,  0, tr_null,
	   mfb(transparent), &iexamine::fswitch, 0x0},
{"cyan switch",         '6', c_cyan,    0, tr_null,
	   mfb(transparent), &iexamine::fswitch, 0x0},
{"purple switch",       '6', c_magenta, 0, tr_null,
	   mfb(transparent), &iexamine::fswitch, 0x0},
{"checkered switch",    '6', c_white,   0, tr_null,
	   mfb(transparent), &iexamine::fswitch, 0x0},
{"tombstone",           'T', c_white,    2, tr_null,
    mfb(transparent)|mfb(thin_obstacle), &iexamine::none, 0x0},
};

const furn_t ufurnlist[num_furniture_types] = { // MUST match enum furn_id above!
{"nothing",             ' ', c_white,   0, -1,
    mfb(transparent), &iexamine::none, 0x0},
{"hay",                 '#', i_brown,   3, 6,
    mfb(transparent)|mfb(container)|mfb(flammable2), &iexamine::none, 0x0},
{"bulletin board",      '6', c_blue,    -10, -1,
    mfb(bashable)|mfb(flammable)|mfb(noitem)|
    mfb(deconstruct), &iexamine::bulletin_board, 0x0},
{"indoor plant",        '^', c_green,   2, 5,
    mfb(container)|mfb(bashable)|mfb(place_item), &iexamine::none, 0x0},
{"bed",                 '#', c_magenta, 3, -1,
    mfb(transparent)|mfb(container)|mfb(flammable2)|
    mfb(deconstruct)|mfb(place_item), &iexamine::none, 0x0},
{"toilet",              '&', c_white,   2, 18,
    mfb(transparent)|mfb(bashable)|mfb(l_flammable), &iexamine::water_source, 0x0},
{"makeshift bed",       '#', c_magenta, 3, 12,
    mfb(transparent)|mfb(bashable)|mfb(flammable2)|
    mfb(deconstruct), &iexamine::none, 0x0},
{"sink",                '&', c_white,   2, 18,
    mfb(transparent)|mfb(bashable)|mfb(l_flammable)|
    mfb(container)|mfb(place_item), &iexamine::none, 0x0},
{"oven",                '#', c_dkgray,  2, 10,
    mfb(transparent)|mfb(bashable)|mfb(l_flammable)|
    mfb(container)|mfb(place_item), &iexamine::none, 0x0},
{"wood stove",          '#', i_red,     2, 10,
    mfb(transparent)|mfb(container)|mfb(fire_container)|
    mfb(suppress_smoke)|mfb(place_item), &iexamine::none, 0x0},
{"fireplace",           '#', i_white,   2, -1,
    mfb(transparent)|mfb(container)|mfb(fire_container)|
    mfb(suppress_smoke)|mfb(place_item), &iexamine::none, 0x0},
{"bathtub",             '~', c_white,   2, 10,
    mfb(transparent)|mfb(bashable)|mfb(l_flammable)|
    mfb(container)|mfb(place_item), &iexamine::none, 0x0},
{"chair",               '#', c_brown,   1, 6,
    mfb(transparent)|mfb(flammable2)|mfb(deconstruct), &iexamine::none, 0x0},
{"arm chair",           'H', c_green,   1, 7,
    mfb(transparent)|mfb(flammable2)|mfb(deconstruct), &iexamine::none, 0x0},
{"sofa",                'H', i_red,     1, 10,
    mfb(transparent)|mfb(flammable2)|mfb(deconstruct), &iexamine::none, 0x0},
{"cupboard",            '#', c_blue,    1, 8,
    mfb(transparent)|mfb(flammable2)|mfb(deconstruct)|
    mfb(container)|mfb(place_item), &iexamine::none, 0x0},
{"trash can",           '&', c_ltcyan,  1, 5,
    mfb(transparent)|mfb(flammable2)|mfb(container)|
    mfb(place_item), &iexamine::none, 0x0},
{"desk",                '#', c_ltred,   1, 8,
    mfb(transparent)|mfb(flammable2)|mfb(deconstruct)|
    mfb(container)|mfb(place_item), &iexamine::none, 0x0},
{"exercise machine",    'T', c_dkgray,  1, 8,
    mfb(transparent)|mfb(deconstruct), &iexamine::none, 0x0},
{"bench",               '#', c_brown,   1, 8,
    mfb(transparent)|mfb(flammable2)|mfb(deconstruct), &iexamine::none, 0x0},
{"table",               '#', c_red,     2, 9,
    mfb(transparent)|mfb(flammable)|mfb(deconstruct), &iexamine::none, 0x0},
{"pool table",          '#', c_green,   2, -1,
    mfb(transparent)|mfb(flammable)|mfb(deconstruct), &iexamine::none, 0x0},
{"counter",	            '#', c_blue,    2, 10,
    mfb(transparent)|mfb(flammable)|mfb(deconstruct), &iexamine::none, 0x0},
{"refrigerator",        '{', c_ltcyan,  -10, 10,
    mfb(container)|mfb(bashable)|mfb(deconstruct)|mfb(place_item), 
    &iexamine::none, 0x0},
{"glass door fridge",   '{', c_ltcyan,  -10, 10,
    mfb(container)|mfb(bashable)|mfb(deconstruct)|mfb(place_item), 
    &iexamine::none, 0x0},
{"dresser",             '{', c_brown,   -10, 8,
    mfb(transparent)|mfb(container)|mfb(flammable)|mfb(bashable)|
    mfb(deconstruct)|mfb(place_item), &iexamine::none, 0x0},
{"locker",              '{', c_ltgray,  -10, 9,
    mfb(container)|mfb(bashable)|mfb(place_item)|
    mfb(deconstruct), &iexamine::none, 0x0},
{"display rack",        '{', c_ltgray,  -10, 8,
    mfb(transparent)|mfb(l_flammable)|mfb(bashable)|mfb(deconstruct)|
    mfb(place_item)|mfb(deconstruct), &iexamine::none, 0x0},
{"book case",           '{', c_brown,   -10, 9,
    mfb(flammable)|mfb(bashable)|mfb(deconstruct)|
    mfb(place_item), &iexamine::none, 0x0},
{"washing machine",     '{', i_white,   -10, 16,
    mfb(container)|mfb(bashable)|mfb(place_item), &iexamine::none, 0x0},
{"dryer",               '{', i_white,   -10, 16,
    mfb(container)|mfb(bashable)|mfb(place_item), &iexamine::none, 0x0},
{"dumpster",	        '{', c_green,   -10, 16,
    mfb(container)|mfb(bashable)|mfb(place_item), &iexamine::none, 0x0},
{"crate",               'X', i_brown,   -10, 14,
    mfb(transparent)|mfb(bashable)|mfb(container)|mfb(sealed)|
    mfb(flammable)|mfb(deconstruct)|mfb(place_item), &iexamine::none, 0x0},
{"open crate",          'O', i_brown,   -10, 12,
    mfb(transparent)|mfb(bashable)|mfb(container)|
    mfb(flammable)|mfb(place_item), &iexamine::none, 0x0},
{"canvas wall",         '#', c_blue,    -10, -1,
    mfb(l_flammable)|mfb(bashable)|mfb(noitem), &iexamine::none, 0x0},
{"canvas flap",         '+', c_blue,    -10, -1,
    mfb(l_flammable)|mfb(bashable)|mfb(noitem), &iexamine::none, 0x0},
{"open canvas flap",    '.', c_blue,    0, -1,
    mfb(transparent), &iexamine::none, 0x0},
{"groundsheet",         ';', c_green,   0, -1,
    mfb(transparent)|mfb(indoors), &iexamine::tent, 0x0},
{"groundsheet",         ';', c_green,   0, -1,
    mfb(transparent)|mfb(indoors), &iexamine::none, 0x0},
{"animalskin wall",     '#', c_brown,   -10, -1,
    mfb(l_flammable)|mfb(bashable)|mfb(noitem), &iexamine::none, 0x0},
{"animalskin flap",     '+', c_white,   -10, -1,
    mfb(l_flammable)|mfb(bashable)|mfb(noitem), &iexamine::none, 0x0},
{"open animalskin flap", '.', c_white,  0, -1,
    mfb(transparent), &iexamine::none, 0x0},
{"animalskin floor",    ';', c_brown,   0, -1,
    mfb(transparent)|mfb(indoors), &iexamine::shelter, 0x0},
{"mutated poppy flower", 'f', c_red,    1, -1,
    mfb(transparent), &iexamine::flower_poppy, 0x0}
};

#endif
